apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argus.fullname" . }}
  labels:
    {{- include "argus.labels" . | nindent 4 }}
data:
  .argus.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}
