apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "argus.fullname" . }}
  labels:
    {{- include "argus.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  suspend: {{ .Values.suspend }}
  jobTemplate:
    spec:
      {{- if .Values.job.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
      {{- end }}
      {{- if .Values.job.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
      {{- end }}
      backoffLimit: {{ .Values.job.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "argus.selectorLabels" . | nindent 12 }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          restartPolicy: OnFailure
          {{- if .Values.serviceAccount.create }}
          serviceAccountName: {{ include "argus.serviceAccountName" . }}
          {{- end }}
          containers:
            - name: argus
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                {{- if .Values.verbose }}
                - "-v"
                {{- end }}
                {{- range .Values.args }}
                - {{ . | quote }}
                {{- end }}
                {{- if .Values.dryRun }}
                - "--dry-run"
                {{- end }}
              envFrom:
                - secretRef:
                    name: {{ include "argus.secretName" . }}
              volumeMounts:
                - name: config
                  mountPath: /app/.argus.yaml
                  subPath: .argus.yaml
                  readOnly: true
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          volumes:
            - name: config
              configMap:
                name: {{ include "argus.fullname" . }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
