{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argus.fullname" . }}
  labels:
    {{- include "argus.labels" . | nindent 4 }}
type: Opaque
stringData:
  ARGUS_GITHUB_TOKEN: {{ .Values.credentials.githubToken | quote }}
  ARGUS_SNYK_TOKEN: {{ .Values.credentials.snykToken | quote }}
  ARGUS_JIRA_URL: {{ .Values.credentials.jiraUrl | quote }}
  ARGUS_JIRA_USERNAME: {{ .Values.credentials.jiraUsername | quote }}
  ARGUS_JIRA_TOKEN: {{ .Values.credentials.jiraToken | quote }}
{{- end }}
